sudo: required
language: generic
services:
  - docker

script:
  - docker build -t jegbertmanh/nvm-chromium:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push jegbertmanh/nvm-chromium:latest
